# Generated by Django 5.2 on 2025-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='photo',
            field=models.ImageField(blank=True, default='43790986.jpg', null=True, upload_to='instructors/photos'),
        ),
    ]
