# Generated by Django 5.2 on 2025-06-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_instructorprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='jop',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=30),
        ),
    ]
