# Generated by Django 5.2 on 2025-05-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_enroll',
            field=models.IntegerField(default=0),
        ),
    ]
